

# This file was *autogenerated* from the file pollard.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_391 = Integer(391); _sage_const_19 = Integer(19); _sage_const_357 = Integer(357); _sage_const_6 = Integer(6)
import random
from sage.all import gcd, primes, ceil, log

def pollard_method(N, B):
    a = random.randint(_sage_const_1 , N - _sage_const_1 )
    d = gcd(a, N)
    if d != _sage_const_1 :
        return d

    b = a
    for l in primes(_sage_const_2 , B + _sage_const_1 ):
        e = ceil(log(N, l))
        E = l**e
        b = power_mod(b, E, N)
        d = gcd(b - _sage_const_1 , N)
        if d != _sage_const_1 :
            if d < N:
                return d
            else:
                return "failure"

    return "failure"

if __name__ == "__main__":
    print(pollard_method(_sage_const_391 , _sage_const_19 ))
    print(pollard_method(_sage_const_357 , _sage_const_6 ))

